export const membersData = [
  {
    email: "sarah.jameson@test.com",
    username: "sarah.jameson",
    name: "Sarah Jameson",
    age: 31,
    created: "2024-08-15",
    lastActive: "2024-09-03",
    bio: "Sarah is a passionate nature lover who spends her weekends hiking the scenic trails of British Columbia. With a background in digital marketing, she enjoys helping small businesses grow their online presence. In her downtime, she enjoys photography and experimenting with new recipes in the kitchen.",
    image: "/",
  },
  {
    email: "karen.robertson@test.com",
    username: "karen.robertson",
    name: "Karen Robertson",
    age: 30,
    created: "2024-08-12",
    lastActive: "2024-09-01",
    bio: "Karen is a fitness enthusiast who has turned her love for running into a half-marathon career. Working as a software engineer, she finds a perfect balance between logic and creativity. Karen also enjoys reading mystery novels and spending quiet evenings with her rescue cat, Shadow.",
    image: "/",
  },
  {
    email: "margo.mclean@test.com",
    username: "margo.mclean",
    name: "Margo McLean",
    age: 33,
    created: "2024-08-22",
    lastActive: "2024-08-29",
    bio: "Margo, a graphic designer with a flair for vibrant, modern art, draws inspiration from the natural beauty of Vancouver. When she's not designing, she loves volunteering at animal shelters and participating in community art projects. Margo’s easy-going personality makes her the go-to person for creative collaborations.",
    image: "/",
  },
  {
    email: "lois.dawson@test.com",
    username: "lois.dawson",
    name: "Lois Dawson",
    age: 32,
    created: "2024-08-18",
    lastActive: "2024-08-30",
    bio: "Lois is an avid traveler who has visited over 20 countries, with her favorite being New Zealand. She works as a UX/UI designer and has a strong passion for user-centered design. In her spare time, Lois enjoys cycling around the city and exploring the Vancouver food scene with friends.",
    image: "/",
  },
  {
    email: "ruthie.anderson@test.com",
    username: "ruthie.anderson",
    name: "Ruthie Anderson",
    age: 29,
    created: "2024-08-21",
    lastActive: "2024-09-02",
    bio: "Ruthie is a wellness coach with a passion for mindfulness and meditation. She loves helping others discover the benefits of a balanced lifestyle. When not working, Ruthie enjoys exploring Vancouver’s vibrant yoga scene and spending quiet mornings by the ocean with her dog, Luna.",
    image: "/",
  },
  {
    email: "todd.bennett@test.com",
    username: "todd.bennett",
    name: "Todd Bennett",
    age: 38,
    created: "2024-08-17",
    lastActive: "2024-09-03",
    bio: "Todd is a software developer who loves coding and building apps that make life easier. Outside of work, Todd enjoys woodworking and has built much of his home furniture. He also loves spending time with his two young children, introducing them to his favorite hobby—camping in the great outdoors.",
    image: "/",
  },
  {
    email: "porter.thompson@test.com",
    username: "porter.thompson",
    name: "Porter Thompson",
    age: 25,
    created: "2024-08-23",
    lastActive: "2024-09-01",
    bio: "Porter is a young entrepreneur with a startup in the tech industry. Passionate about innovation, he is always on the lookout for new challenges. In his free time, Porter enjoys kayaking, attending tech meetups, and hosting game nights with friends at his home in Vancouver.",
    image: "/",
  },
  {
    email: "mayo.wilson@test.com",
    username: "mayo.wilson",
    name: "Mayo Wilson",
    age: 42,
    created: "2024-08-14",
    lastActive: "2024-08-30",
    bio: "Mayo is a dedicated community worker who is passionate about social causes. With a background in social work, Mayo is deeply involved in helping the homeless in Vancouver. He enjoys long hikes, playing soccer, and is always up for an adventure, whether it's traveling or exploring new local spots.",
    image: "/",
  },
  {
    email: "skinner.jones@test.com",
    username: "skinner.jones",
    name: "Skinner Jones",
    age: 40,
    created: "2024-08-19",
    lastActive: "2024-09-01",
    bio: "Skinner, a mechanical engineer, has always had a passion for building things from scratch. He enjoys tinkering with old cars and dreams of restoring a classic Mustang one day. In his spare time, he enjoys watching hockey and organizing weekend road trips with friends.",
    image: "/",
  },
  {
    email: "davis.harrison@test.com",
    username: "davis.harrison",
    name: "Davis Harrison",
    age: 28,
    created: "2024-08-20",
    lastActive: "2024-09-03",
    bio: "Davis is a high school teacher who specializes in history and social sciences. He loves sharing his passion for history with his students. On weekends, Davis enjoys hiking with his dog and practicing photography, capturing the stunning landscapes of Vancouver’s mountains and forests.",
    image: "/",
  },
];
